export type QuestionType =
    | "select"
    | "multi-select"
    | "range"
    | "text"
    | "email"
    | "info";

export interface Question {
    id: string;
    type: QuestionType;
    label: string;
    section: string;
    description?: string;
    options?: string[];
    min?: number;
    max?: number;
    step?: number;
    condition?: (answers: Record<string, any>) => boolean;
    required?: boolean;
    placeholder?: string;
}

export const SECTIONS = [
    "Profil",
    "Rôle & Sites",
    "Vie aux Jeux",
    "Opérationnel",
    "Futur",
    "Divers",
];

export const QUESTIONS: Question[] = [
    // 1) Profil
    {
        id: "age",
        type: "select",
        section: "Profil",
        label: "Catégorie d'âge",
        options: ["18 – 25 ans", "26 – 35 ans", "36 – 45 ans", "46 – 55 ans", "56 – 65 ans", "+ 65 ans"],
        required: true,
    },
    {
        id: "genre",
        type: "select",
        section: "Profil",
        label: "Genre",
        options: ["Femme", "Homme", "Non binaire"],
        required: true,
    },
    {
        id: "region",
        type: "select",
        section: "Profil",
        label: "Zone géographique",
        options: [
            "Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Bretagne", "Centre-Val de Loire",
            "Corse", "Grand Est", "Hauts-de-France", "Île-de-France", "Normandie",
            "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d'Azur",
            "Guadeloupe", "Martinique", "Guyane", "La Réunion", "Mayotte",
            "Expatriés français (précisez le pays)",
        ],
        required: true,
    },
    {
        id: "region_expat",
        type: "text",
        section: "Profil",
        label: "Précisez votre pays d'expatriation",
        condition: (a) => a.region?.includes("Expatriés"),
        required: true,
    },
    {
        id: "situation_handicap",
        type: "select",
        section: "Profil",
        label: "Êtes-vous en situation de handicap ?",
        options: ["Oui", "Non", "Je ne souhaite pas répondre"],
        required: true,
    },
    {
        id: "accompagnement",
        type: "select",
        section: "Profil",
        label: "Aviez-vous besoin d'un accompagnement particulier durant votre mission ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "accompagnement_details",
        type: "text",
        section: "Profil",
        label: "Si oui, lequel :",
        condition: (a) => a.accompagnement === "Oui",
        required: true,
    },
    {
        id: "paris2024",
        type: "select",
        section: "Profil",
        label: "Étiez-vous volontaire aux Jeux d'été de Paris 2024 ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "autres_jo",
        type: "select",
        section: "Profil",
        label: "Aviez-vous participé à d'autres Jeux olympiques ou paralympiques d'été comme volontaire ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "autres_hiver",
        type: "select",
        section: "Profil",
        label: "Aviez-vous déjà participé à d'autres Jeux olympiques ou paralympiques d'hiver comme volontaire ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "benevole_hiver",
        type: "select",
        section: "Profil",
        label: "Êtes-vous bénévole lors d'événements internationaux de sports d'hiver ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "reserviste",
        type: "select",
        section: "Profil",
        label: "Étiez-vous réserviste avant d'obtenir une mission ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "adherent_vf",
        type: "select",
        section: "Profil",
        label: "Êtes-vous adhérent de l'association Volontaires français ?",
        options: ["Oui", "Non"],
        required: true,
    },
    // 2) Rôle & Sites
    {
        id: "type_jeux",
        type: "select",
        section: "Rôle & Sites",
        label: "Vous étiez missionné(e) :",
        options: ["Sur les Jeux Olympiques", "Sur les Jeux Paralympiques", "Sur les deux"],
        required: true,
    },
    {
        id: "sites_zones",
        type: "multi-select",
        section: "Rôle & Sites",
        label: "Quel était votre site d'affectation ?",
        options: ["MILAN", "CORTINA D'AMPEZZO", "VERONA", "VAL DI FIEMME", "VALTELLINA", "ANTERSELVA"],
        required: true,
    },
    {
        id: "milan_venues",
        type: "multi-select",
        section: "Rôle & Sites",
        label: "Précisez votre site à MILAN",
        condition: (a) => a.sites_zones?.includes("MILAN"),
        options: [
            "San Siro – Cérémonie d'ouverture",
            "Milano Speed Skating Stadium – Patinage de vitesse",
            "Milano Ice Hockey Arena Santa Giulia – Hockey sur glace (tournoi masculin et toutes les finales)",
            "Milano Rho Hockey Arena – Hockey sur glace (premiers matchs masculins), para hockey sur glace",
            "Ice Skating Arena – Patinage de vitesse sur piste courte / Patinage artistique",
            "Village olympique", "Chauffeur", "Game family Assistant", "Accréditations / Uniformes", "Media Center", "Autres",
        ],
        required: true,
    },
    {
        id: "milan_venues_autres",
        type: "text",
        section: "Rôle & Sites",
        label: "Précisez votre site à MILAN (Autres)",
        condition: (a) => a.sites_zones?.includes("MILAN") && a.milan_venues?.includes("Autres"),
        required: true,
    },
    {
        id: "cortina_venues",
        type: "multi-select",
        section: "Rôle & Sites",
        label: "Précisez votre site à CORTINA D'AMPEZZO",
        condition: (a) => a.sites_zones?.includes("CORTINA D'AMPEZZO"),
        options: [
            "Tofane Alpine Skiing Centre – Ski alpin / Para ski alpin / Para snowboard",
            "Cortina Sliding Centre – Bobsleigh / Skeleton / Luge",
            "Cortina Curling Olympic Stadium – Curling / Curling fauteuil",
            "Village olympique", "Chauffeur", "Game family Assistant", "Accréditations / Uniformes", "Media Center", "Autres",
        ],
        required: true,
    },
    {
        id: "cortina_venues_autres",
        type: "text",
        section: "Rôle & Sites",
        label: "Précisez votre site à CORTINA D'AMPEZZO (Autres)",
        condition: (a) => a.sites_zones?.includes("CORTINA D'AMPEZZO") && a.cortina_venues?.includes("Autres"),
        required: true,
    },
    {
        id: "verona_venues",
        type: "multi-select",
        section: "Rôle & Sites",
        label: "Précisez votre site à VERONA",
        condition: (a) => a.sites_zones?.includes("VERONA"),
        options: [
            "Arènes de Vérone – Cérémonies clôture des Jeux Olympiques et ouverture des Jeux Paralympiques",
            "Autres",
        ],
        required: true,
    },
    {
        id: "verona_venues_autres",
        type: "text",
        section: "Rôle & Sites",
        label: "Précisez votre site à VERONA (Autres)",
        condition: (a) => a.sites_zones?.includes("VERONA") && a.verona_venues?.includes("Autres"),
        required: true,
    },
    {
        id: "fiemme_venues",
        type: "multi-select",
        section: "Rôle & Sites",
        label: "Précisez votre site à VAL DI FIEMME",
        condition: (a) => a.sites_zones?.includes("VAL DI FIEMME"),
        options: [
            "Predazzo Ski Jumping Stadium – Saut à ski / Combiné nordique",
            "Tesero Cross-Country Skiing Stadium – Ski de fond / Combiné nordique / Para ski de fond / Para biathlon",
            "Village olympique", "Chauffeur", "Game family Assistant", "Accréditations / Uniformes", "Media Center", "Autres",
        ],
        required: true,
    },
    {
        id: "fiemme_venues_autres",
        type: "text",
        section: "Rôle & Sites",
        label: "Précisez votre site à VAL DI FIEMME (Autres)",
        condition: (a) => a.sites_zones?.includes("VAL DI FIEMME") && a.fiemme_venues?.includes("Autres"),
        required: true,
    },
    {
        id: "valtellina_venues",
        type: "multi-select",
        section: "Rôle & Sites",
        label: "Précisez votre site à VALTELLINA",
        condition: (a) => a.sites_zones?.includes("VALTELLINA"),
        options: [
            "Livigno Aerials & Moguls – Ski freestyle",
            "Livigno Snow Park – Snowboard / Ski acrobatique",
            "Bormio Stelvio – Ski alpin / Ski alpinisme",
            "Village olympique", "Chauffeur", "Game family Assistant", "Accréditations / Uniformes", "Media Center", "Autres",
        ],
        required: true,
    },
    {
        id: "valtellina_venues_autres",
        type: "text",
        section: "Rôle & Sites",
        label: "Précisez votre site à VALTELLINA (Autres)",
        condition: (a) => a.sites_zones?.includes("VALTELLINA") && a.valtellina_venues?.includes("Autres"),
        required: true,
    },
    {
        id: "anterselva_venues",
        type: "multi-select",
        section: "Rôle & Sites",
        label: "Précisez votre site à ANTERSELVA",
        condition: (a) => a.sites_zones?.includes("ANTERSELVA"),
        options: [
            "Südtirol Arena (Anterselva / Antholz) – Biathlon",
            "Village olympique", "Chauffeur", "Game family Assistant", "Accréditations / Uniformes", "Media Center", "Autres",
        ],
        required: true,
    },
    {
        id: "anterselva_venues_autres",
        type: "text",
        section: "Rôle & Sites",
        label: "Précisez votre site à ANTERSELVA (Autres)",
        condition: (a) => a.sites_zones?.includes("ANTERSELVA") && a.anterselva_venues?.includes("Autres"),
        required: true,
    },
    {
        id: "mission_principale",
        type: "select",
        section: "Rôle & Sites",
        label: "Quelle était votre mission principale ?",
        options: ["EVS (Service aux spectateurs)", "Game family Assistant", "Accréditations / Uniformes", "Médias", "Sports", "Chauffeur", "Fonction support", "Autres"],
        required: true,
    },
    {
        id: "mission_autres",
        type: "text",
        section: "Rôle & Sites",
        label: "Veuillez préciser votre mission",
        condition: (a) => a.mission_principale?.startsWith("Autres"),
        required: true,
    },
    {
        id: "redéployé",
        type: "select",
        section: "Rôle & Sites",
        label: "Avez-vous été redéployé(e) sur une autre mission durant les Jeux ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "responsable_equipe",
        type: "select",
        section: "Rôle & Sites",
        label: "Étiez-vous responsable d'une équipe durant votre mission ?",
        options: ["Oui", "Non"],
        required: true,
    },
    // 3) Vie aux Jeux
    {
        id: "satisfaction_globale",
        type: "range",
        section: "Vie aux Jeux",
        label: "Êtes-vous satisfait(e) de votre expérience globale ?",
        description: "1 = Pas du tout | 10 = Tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "satisfaction_integration",
        type: "range",
        section: "Vie aux Jeux",
        label: "Êtes-vous satisfait(e) de votre intégration au sein des Jeux de Milano Cortina ?",
        description: "1 = Pas du tout | 10 = Tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "satisfaction_gestion",
        type: "range",
        section: "Vie aux Jeux",
        label: "Êtes-vous satisfait(e) de votre gestion par les équipes de Milano Cortina ?",
        description: "1 = Pas du tout | 10 = Tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "satisfaction_attentes",
        type: "range",
        section: "Vie aux Jeux",
        label: "Votre expérience a-t-elle répondu à vos attentes ?",
        description: "1 = Pas du tout | 10 = Tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "difficulte_logement",
        type: "range",
        section: "Vie aux Jeux",
        label: "Avez-vous eu des difficultés à trouver un logement ?",
        description: "1 = Pas du tout | 10 = Oui, tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "prix_logement_nuit",
        type: "select",
        section: "Vie aux Jeux",
        label: "Fourchette de prix par nuit de votre logement pour la période de mission :",
        options: ["1 - 50 €", "51 - 75 €", "76 - 100 €", "101 - 125 €", "126 - 150 €", "151 - 175 €", "176 - 200 €", "201 - 300 €", "+ 300 €", "J'ai été logé gratuitement"],
        required: true,
    },
    {
        id: "prix_logement_global",
        type: "select",
        section: "Vie aux Jeux",
        label: "Fourchette de prix du coût global de votre logement pour la période de mission :",
        options: ["1 – 500 €", "501 – 700 €", "701 – 1 000 €", "1 001 – 1 300 €", "1 301 – 1 500 €", "1 501 – 1 800 €", "1 801 – 2 000 €", "+ de 2 000 €", "J'ai été logé(e) gratuitement"],
        required: true,
    },
    {
        id: "annulation_logement",
        type: "select",
        section: "Vie aux Jeux",
        label: "Avez-vous été victime d'une annulation de location par le propriétaire ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "fraude_logement",
        type: "select",
        section: "Vie aux Jeux",
        label: "Avez-vous été victime d'une location frauduleuse ou d'un logement insalubre ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "temps_transport",
        type: "select",
        section: "Vie aux Jeux",
        label: "Temps moyen journalier pour rejoindre votre site (trajet aller) :",
        options: ["1 à 30 min", "31 à 45 min", "46 à 60 min", "61 à 75 min", "76 à 90 min", "+ de 90 min"],
        required: true,
    },
    {
        id: "transport_acceptable",
        type: "range",
        section: "Vie aux Jeux",
        label: "Ce temps de transport était :",
        description: "1 = Pas du tout acceptable | 5 = Neutre | 10 = Très acceptable",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "satisfaction_transport",
        type: "range",
        section: "Vie aux Jeux",
        label: "Comment jugez-vous l'offre de transport proposée par Milano Cortina ?",
        description: "1 = Pas du tout satisfait(e) | 5 = Neutre | 10 = Très satisfait(e)",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "importance_transport",
        type: "range",
        section: "Vie aux Jeux",
        label: "Les facilités de transport offertes par un comité d'organisation sont, pour vous :",
        description: "1 = Pas du tout importantes | 5 = Neutre | 10 = Très importantes",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "importance_repas",
        type: "range",
        section: "Vie aux Jeux",
        label: "La qualité des repas proposés est, pour vous :",
        description: "1 = Pas du tout importante | 5 = Neutre | 10 = Très importante",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "satisfaction_evenements",
        type: "range",
        section: "Vie aux Jeux",
        label: "Comment jugez-vous les événements à destination des volontaires mis en place par le COJO ?",
        description: "1 = Pas du tout satisfait(e) | 5 = Neutre | 10 = Très satisfait(e)",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "importance_evenements",
        type: "range",
        section: "Vie aux Jeux",
        label: "Les événements volontaires sont, pour vous :",
        description: "1 = Pas du tout importants | 5 = Neutre | 10 = Très importants",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "periode_role",
        type: "select",
        section: "Vie aux Jeux",
        label: "À quelle période avez-vous reçu votre rôle ?",
        options: [
            "Avant septembre 2025", "Septembre 2025", "Octobre 2025", "Novembre 2025",
            "1er au 15 décembre 2025", "16 au 31 décembre 2025",
            "1er au 15 janvier 2026", "16 au 31 janvier 2026", "Février 2026", "Je ne me souviens plus",
        ],
        required: true,
    },
    {
        id: "periode_agenda",
        type: "select",
        section: "Vie aux Jeux",
        label: "À quelle période avez-vous reçu votre planning ?",
        options: [
            "Avant décembre 2025", "Décembre 2025",
            "1er au 15 janvier 2026", "16 au 31 janvier 2026", "Février 2026", "Je ne me souviens plus",
        ],
        required: true,
    },
    {
        id: "difficulte_role_logement",
        type: "range",
        section: "Vie aux Jeux",
        label: "La date d'obtention de votre rôle vous a-t-elle posé des difficultés pour trouver un logement ?",
        description: "1 = Pas du tout | 10 = Oui, tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "difficulte_agenda_logement",
        type: "range",
        section: "Vie aux Jeux",
        label: "La date d'obtention de votre planning vous a-t-elle posé des difficultés pour trouver un logement ?",
        description: "1 = Pas du tout | 10 = Oui, tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    // 4) Opérationnel
    {
        id: "vst_training",
        type: "select",
        section: "Opérationnel",
        label: 'Au préalable, avez-vous pu assister à la "Venue Specific Training" sur site ?',
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "satisfaction_checkin",
        type: "select",
        section: "Opérationnel",
        label: "En mission, le check-in vous a-t-il satisfait (accueil, temps d'attente, fluidité au desk, cadeaux, bon repas…) ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "checkout_realise",
        type: "select",
        section: "Opérationnel",
        label: "Avez-vous réalisé des check-out ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "centre_volontaire",
        type: "select",
        section: "Opérationnel",
        label: "Disposiez-vous d'un centre volontaire avec un coordinateur volontaires ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "points_rdv_clairs",
        type: "select",
        section: "Opérationnel",
        label: "Lors de vos prises de missions, les points de rendez-vous étaient-il clairs ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "superviseur_joignable",
        type: "select",
        section: "Opérationnel",
        label: "Votre superviseur était-il facilement joignable en cas de difficulté ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "formation_evacuation",
        type: "select",
        section: "Opérationnel",
        label: "Avez-vous été formé sur site aux cheminements d'évacuation / sorties de secours ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "eco_responsable",
        type: "range",
        section: "Opérationnel",
        label: "Lors de vos missions, avez-vous contribué à rendre les Jeux plus éco-responsables ?",
        description: "1 = Non pas du tout | 5 = Neutre | 10 = Oui tout à fait",
        min: 1, max: 10, step: 1, required: true,
    },
    {
        id: "intensite_mission",
        type: "select",
        section: "Opérationnel",
        label: "Sur l'intensité de vos missions, étiez-vous ?",
        options: ["En sur-nombre", "En sous-nombre", "Au bon nombre"],
        required: true,
    },
    {
        id: "rotation_poste",
        type: "select",
        section: "Opérationnel",
        label: "Une rotation de poste était-elle organisée sur vos missions ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "info_materiel",
        type: "select",
        section: "Opérationnel",
        label: "En termes de communication, disposiez-vous des bonnes informations / du bon matériel pour effectuer vos missions ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "equipe_changeante",
        type: "select",
        section: "Opérationnel",
        label: "La composition de votre équipe changeait-elle tous les jours ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "eloignement_degrade",
        type: "select",
        section: "Opérationnel",
        label: "L'éloignement des sites les uns des autres a-t-il dégradé votre expérience ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "point_fort",
        type: "text",
        section: "Opérationnel",
        label: "Selon vous, quel a été le point fort de l'organisation locale ?",
        required: false,
    },
    {
        id: "appreciations",
        type: "text",
        section: "Opérationnel",
        label: "Quels sont les 3 éléments que vous avez le plus appréciés lors de cette expérience ?",
        required: false,
    },
    {
        id: "deceptions",
        type: "text",
        section: "Opérationnel",
        label: "Quels sont les 3 points qui ont réduit votre expérience ?",
        required: false,
    },
    {
        id: "conseil_alpes2030",
        type: "text",
        section: "Opérationnel",
        label: "Si vous deviez donner un conseil aux futurs organisateurs des Alpes 2030 concernant la gestion des volontaires, quel serait-il ?",
        required: false,
    },
    // 5) Futur
    {
        id: "candidat_la2028",
        type: "select",
        section: "Futur",
        label: "Serez-vous candidat(e) pour être volontaire aux Jeux d'été de Los Angeles 2028 ?",
        options: ["Oui", "Non", "Je réfléchis encore"],
        required: true,
    },
    {
        id: "candidat_alpes2030",
        type: "select",
        section: "Futur",
        label: "Serez-vous candidat(e) pour être volontaire aux Jeux d'hiver des Alpes françaises 2030 ?",
        options: ["Oui", "Non", "Je réfléchis encore"],
        required: true,
    },
    {
        id: "candidat_brisbane2032",
        type: "select",
        section: "Futur",
        label: "Serez-vous candidat(e) pour être volontaire aux Jeux d'été de Brisbane 2032 ?",
        options: ["Oui", "Non", "Je réfléchis encore"],
        required: true,
    },
    {
        id: "autres_elements",
        type: "text",
        section: "Futur",
        label: "D'autres éléments à ajouter ?",
        placeholder: "Espace libre d'expression...",
        required: false,
    },
    // 6) Divers
    {
        id: "connaissance_association",
        type: "select",
        section: "Divers",
        label: "Connaissez-vous l'association Volontaires français ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "recevoir_resultats",
        type: "select",
        section: "Divers",
        label: "Souhaitez-vous recevoir les résultats de cette enquête ?",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "rejoindre_association",
        type: "select",
        section: "Divers",
        label: "Je souhaite également recevoir des informations pour rejoindre l'association Volontaires Français.",
        options: ["Oui", "Non"],
        required: true,
    },
    {
        id: "email",
        type: "email",
        section: "Divers",
        label: "Merci d'indiquer votre adresse e-mail (facultatif) :",
        condition: (a) => a.recevoir_resultats === "Oui" || a.rejoindre_association === "Oui",
        required: false,
    },
    {
        id: "merci",
        type: "info",
        section: "Divers",
        label: "Un grand merci !",
        description: "Cliquez sur envoyer pour transmettre vos réponses.",
    },
];
